#+TITLE: Dejarse Golpear no es Ético
#+LANGUAGE: es
#+AUTHOR: David Arroyo Menéndez

Hoy me apetece cuestionar la eticidad de la figura de Jesucristo y de
otros líderes pacifistas a los que inspiró desde el punto de vista de
la eticidad de dejarse golpear. A muchas personas les inspiró el hecho
de poner la otra mejilla cuando le golpearon, o llevar su propia cruz
en el paso de semana santa.

Por coger alguna definición de ética, he escogido la de Kant en el
imperativo categórico:

+ Obra sólo según una máxima tal, que puedas querer al mismo tiempo
  que se torne en ley universal
+ Obra de tal modo que trates a la humanidad, tanto en tu persona como
  en la de cualquier otro, siempre como un fin y nunca solamente como
  un medio.
+ Obra como si por medio de tus máximas fueras siempre un miembro
  legislador en un reino universal de los fines.

Esto desde mi punto de vista, es básicamente actúa de una manera que
puedas ser tu feliz y que genere felicidad colectiva. 

La actitud de Jesucristo era enfrentarse a la autoridad con denuncia
política y extrema coherencia amando a sus semejantes e incluso a sus
enemigos y, por supuesto, al resto de la humanidad. Tanta fué su
"coherencia" que la llevó al punto de dejarse matar. Esto de dejarse
matar es obvio que atenta en contra de su felicidad personal y la
historia demuestra que el cristianismo fué vencido en su autoridad
moral debido a la jerarquización y complicidad con los estados y el
poder por un lado y asesinando o golpeando con fuerza a los coherentes.

Si Jesucristo intuía atentado desde el gobierno, involucrando en el
caso a alguno de sus semejantes (Judas), hubiera sido más inteligente
para él y para el mundo haber escapado, quizás habiéndose llevado a un
leal para reestructurar el movimiento. Esta actitud fué triunfal para
que se recordara su actitud durante miles de años, pero desde la
derrota moral en el momento en que el emperador romano ......... se
pasara al cristianismo. 

Un movimiento antiautoritario que no se deja golpear es el
anarcosindicalista, aquí la estrategia es la lucha desde los puestos
de trabajo organizando a la clase trabajadora en asambleas y luchando
desde la acción directa (huelga, boicot, sabotaje). La CNT llegó a
convertirse en una gran central sindical donde patronos y políticos
atentaban contra anarcosindicalistas y anarcondicalistas contra estos,
después llegó el alzamiento fascista contra la república, las y los
anarcosindicalistas se opusieron al mismo en las calles y debido a su
valor, el gobierno republicano convirtió a 4 anarcosindicalistas en 3
ministros y 1 ministra, al tiempo que se organizaban las
colectividades. La guerra civil se perdió... Tal vez, fuera necesario
un anarcosindicalismo sin cabezas visibles (por ej: sin
secretarios/as), para evitar la incoherencia de que un movimiento que
busca acabar con el poder acabe siendo parte del poder.

