#+TITLE: Practical Elasticsearch
#+LANGUAGE: es
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/org.css" />
#+AUTHOR: David Arroyo Menéndez
#+DATE: 26/03/2018

[[http://www.davidam.com][Volver a davidam.com]]

* Introduction

This document is only my personal notes about this software.

Elasticsearch is a highly scalable open-source full-text search and
analytics engine. It allows you to store, search, and analyze big
volumes of data quickly and in near real time. It is generally used as
the underlying engine/technology that powers applications that have
complex search features and requirements.

* Installation

https://www.elastic.co/guide/en/elasticsearch/reference/current/_installation.html

* Checking 
#+BEGIN_SRC bash
http://localhost:9200/
#+END_SRC

* List indexes
#+BEGIN_SRC bash
http://localhost:9200/_cat/indices
#+END_SRC

* List indexes in json
#+BEGIN_SRC bash
$ curl 'http://localhost:9200/_cat/indices?pretty' -H "Accept: application/json"
#+END_SRC

* Show an index
#+BEGIN_SRC bash
$ wget http://localhost:9200/dam-index/
#+END_SRC

* Searching in an index
#+BEGIN_SRC bash
$ wget -c http://localhost:9200/dam-index/_search
#+END_SRC

* The cluster state API allows to get a comprehensive state information of the whole cluster.
#+BEGIN_SRC bash
$ wget http://localhost:9200/_cluster/state
#+END_SRC 

* Master
#+BEGIN_SRC bash
http://localhost:9200/_cat/master?v
#+END_SRC

* Show nodes
#+BEGIN_SRC bash
$ wget -c http://localhost:9200/_cat/nodes?h=ip,port,heapPercent,name
$ curl http://localhost:9200/_cat/nodes?v
#+END_SRC

* Show cluster health
#+BEGIN_SRC bash
http://localhost:9200/_cluster/health
#+END_SRC

* Elasticdump
** json to the index
$ elasticdump --input=git_openstack_data.json --output=http://localhost:9200 --output-index=dam-index --type=data
$ elasticdump --input=git_openstack_mapping.json --output=http://localhost:9200 --output-index=dam-index --type=mapping
** index data to json
$ elasticdump  --input=http://production.es.com:9200/my_index --output=/data/my_index_mapping.json --type=mapping
$ elasticdump  --input=http://production.es.com:9200/my_index --output=/data/my_index.json --type=data

* License
Copyright (C) 2018 David Arroyo Menendez
    Permission is granted to copy, distribute and/or modify this document
    under the terms of the GNU Free Documentation License, Version 1.3
    or any later version published by the Free Software Foundation;
    with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
    A copy of the license is included in [[https://www.gnu.org/copyleft/fdl.html][GNU Free Documentation License]].

[[https://www.gnu.org/copyleft/fdl.html][file:https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/GFDL_Logo.svg/200px-GFDL_Logo.svg.png]]
