#+TITLE: Free Software is Activism
#+LANGUAGE: en
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/org.css" />
#+AUTHOR: David Arroyo Menéndez

* Introduction

This article was published in [[http://www.diagonalperiodico.net/saberes/software-libre-es-activismo.html][Diagonal newspaper]], originally, now it
contains some improvements.

In September of 2012 I did present a qualitative work to finish a
master degree published in http://www.davidam.com/docu/tfm.pdf about
social movements and new technologies in Madrid. A question in the
interviews was "What technological tools you have incorporated in
relation with you political activism?".

Only people very closed with the hacktivism make the relathionship
with free software such as gimp, or gnupg and nobody added use or
develop free software in general. The broad answer was the use of
social networks specially Facebook or Twitter.

I as GNU activist and anarchist I would like a reflection about the
dangerous that suppose to the social movements the relations between
the activism and the use of centralized and propietary social networks
(as Twitter and Facebook) and forget that promote the free software is
the best option to make political activism using technology in a smart
way.

* Don't hate the media become the media

That's the slogan to spread the independent media in the ninenties and
starting XXI century: newspapers in a network called Internet where
anyone become consumer or producer in a fast way and projects as
Indymedia, Sindominio, Ourproject, Riseup, etc. implements this
ideas. Although the Indymedia was the way to explain things in a
global fight against the capitalism.

But, what happens with Facebook and Twitter?. Now, the slogan from the
capitalism is "If they are the media, they will be the product". And
that's exactly what happens with the people making retweets, put likes
in Facebook and many people is happy, there are wars in the arabian
worlds that becomes democracies with very similarities and defects to
the occidental democracies and other time becomes awful civil wars. In
Spain, we have found the 15 May Movement growing and decreasing as a
globe, now is the turn to trade unions with similiar effects.

But, what is the reason? the social networks? or the massive attacks
to the workers?. The problem is that with the social networks who is
controlling this media are doing a good speculative work, so critice a
party is similar to invest in trade actions and the experts in data
mining of rich people, bank directors, or politicians make the
investments and 1% of people is more and more rich and the 99% is poor
and more poor.

How can we break the loop? breaking with the capitalism and making the
collectivist anarchism, such as 30's years in Spain. But the game
rules has changed, now we have technology, what can we do it?. To
spread the word, we have technology and we can use it as in the
nineties, but becoming the media and don't the products. In this sense
use federative free social networks (identi.ca, n-1.cc, etc.) is a
possible coherent way in this times.

* What's the Free Software? What's his paper?

The Free Software is defined such as software that gives some freedoms
to his users: use, copy, modify and redistribute modified copies. So,
we can understand the free software as collective property generated
by the users and developers.

Although, from the Open Source philosophy, this problem has changed
until that if the Free Software continues being collective property,
sometimes is not being generated by the real interests of users and
developers, it's generated by the market interest, with especulative
criteria and financial bumbles in a similar way than another market
product.

So, the Open Source philosophy, drop the ethical arguments about if is
reasonable or don't use Free Software, the only argument will be if
technically is or don't a good option, if is a good business and
another similar arguments. But they don't think if it's good the good
common, it's out of the discourse. Many corporations has done good
contributions creating Free Software products from this philosophy,
but sometimes mixed with the philosopy of the propietary software:
Ubuntu, Android, etc.

In the capitalist world, the triumph of the rentability and the
technicity is strong, but finally the original argument about create
software looking for social utility to the people who use and develop
this software has been abolished

Today, there are many communities as GNU, Debian, etc who is loyals to
the software production looking social utility, instead of the
economical rentability in the short time. It's not easy think in the
long time and go out from the capitalism in the technological or in
another field of the life, but is right to reach the collective
happiness and finish with the current strong unequalities.

So, when someone ask you: What tecnological tools has incorporated
from your political activism? you can answer, I use Free Software
based on community, such as [[https://www.gnu.org/software/emacs/][GNU Emacs]], [[http://www.debian.org/][Debian]], [[https://trisquel.info/][Trisquel]], [[http://www.gimp.org/][Gimp]], o [[http://www.gnupg.org/][GPG]]
because I want that the software world is organized as anarchists
collectivities.

* License
This document is under a [[http://creativecommons.org/licenses/by-sa/3.0/deed][Creative Commons Reconocimiento Unported 3.0]]

[[http://creativecommons.org/licenses/by-sa/3.0/deed][file:http://i.creativecommons.org/l/by-sa/3.0/80x15.png]]
