#+TITLE: Versos escondidos a Koro Castellano. No hay nada más fuerte que el amor verdadero
#+LANGUAGE: es
#+AUTHOR: David Arroyo Menéndez
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/org.css" />
#+BABEL: :results output :session

[[http://www.davidam.com][Come back to davidam.com]]

Esta historia es pura ficción, cualquier parecido con la realidad es
pura coincidencia.

Por favor, no lea las secciones poemacs si no sabe programar

* Poemas a Koro (I)
Le veo liderar

con Amazon azul oscuro y

la sonrisa del dorado

y así mi corazón corre alocado


Deme una oportunidad

para construir

Amazon Universidad


Que salgan doctorandos

con doctoras, con doctores,

con liderazgo universal,

nadie se va a enfadar.


Yo a usted le quiero ...

ayudar ...

Pero me dan miedo

quienes no le quieren ná

...

* Poemas a Koro (II)
Ví a Andi

y dí

¿Encontrará la verdadera D

a la verdadera Í?

Id,

Calla cadete,

únete a KDE.

Dime

¿Qué?

Yo soy de unir.

* Poemas a Koro (III)

Libros, libros y más libros

Y al final todos los contenidos,

música, vídeos,

dvds de mil amores,

ordenadores,

no son difamaciones,

son obras de trabajadoras y trabajadores

* Poemas a Koro (IV)

Una mujer, un objetivo,

liderazgo internacional,

tiene sentido,

valores, economía,

ecuaciones,

fotos, simpatía,

razones.

Una distribución para todas las organizaciones

* Poemas a Koro (V)

¿Enamorado?

Y motivado!

Aquí se trabaja,

No nos gusta estar parados,

Pensamiento divertido,

Sonrientes, cayendo bien a la gente,

No nos vamos a cansar,

Estamos para triunfar

* Poemas a Koro (VI)

¿Qué me dirá si le digo libros libres?

Proponga, plantee, 

Encontraremos la ecuación que más conviene,

Sopesamos gastos e ingresos,

Planteamos buenos precios.

* Poemas a Koro (VII)

¿Es este un sueño norteamericano?

Queremos ganar en todos los mercados,

España, Japón, Korea,

pero también China o Guinea,


Déjame que te seduzca,

hazlo rentable,

que se reproduzca.

* Poemas a Koro (VIII)

Una mujer que es un monumento,

con el corazón en el parlamento,

en su familia,

en los buenos sentimientos,

¿Qué más queremos?


¡Koro Castellano!

una mujer de cuento.


* Poemas a Koro (IX)

Koro te encuentro en Vogue

y en la prensa,

pero no en la Wikipedia


¡Será que no interesa!


No amas ese debate,

Ni esa protesta.

Te enseñaría a una 

que sí te besa.


Y a mas de una y a más de dos

que cuando te hablo,

siento que hablo cerca de Dios.

* Poemas a Koro (X)

A Koro todos le van a querer,

nadie me va a convencer contra usted,

el lechero, el político,

el vecino que habla de usted,

Yo sí le sé querer,

Nadie nos debe ofender



¿Y esos de todostuslibros?,

libreros unidos, con ánimo de victimismo,

traficantes de un mundo desaparecido,

Amazon ha vencido,

Ellas y ellos han sonreido.



¿Es lulu.com una revolución?

Nos sirve para un revolcón,

Idea locuaz la de la libertad,

Nosotros la podríamos comercializar,

liderar, mejorar y ampliar,

hágame el amor, pero de verdad

* Poemas a Koro (XI)
Sé que tenemos un sueño escondido,

el del ecofeminismo,

es porque tuvimos corazoncito,

no nos estorba, así nos damos más amorcito,

alegría, confianza inversora,

sí, me gusta tratarle como a una gran señora.

* Poemacs a Koro (I)

K: Mira esa te has fijado?

Una nueva ha llegado

D: La he detectado

D: De los pi peta kappa

D: La he recordado!

D: Ese grupo universitario

K: Lucía se hace llamar y Santamaría apedillar

D: Ese no era el nombre ... ¿Qué debe pasar? ... Lo voy a investigar

D: nombres, sexo,ligo,agujeros negros,
D: ¿de qué va todo esto?
D: Lucía y Helena, son las protagonistas, de la peli que excita,"Lucía y el Sexo" 
D: Ya recuerdo!
D: Clama al cielo, sexo científico, ya ni vengo
D: con Software Libre, purifiquemos todo esto
D: Stallman ha llamado a una santa inquisición desde que Ian Murdock se suicidó
K: ¿Qué ha ocurrido? ¿Qué ha pasado?
D: Me dicen que él solo se ha marchado
D: Uno que dimite cuando el pueblo, sí le admite.
D: Damegender el software se va a llamar, no lo voy a parar de desarrollar
D: Hemos calculado que en GNU/Linux
D: Las mujeres casi se han exterminado
D: Y esa debe ser la razón por la que casi siempre hablo con algún varón
D: Difícil va a ser ligar si a las mujeres no llegamos a hablar.
K: Homosexualidad han recomendadoa a Turing le fue fantástico
D: Murió envenenado
D: Programar en Python, me lo ha recordado


* Poemas a Koro (XII)

D: Estaba en mi balcón y vaya un follón,

D: verde paz apareció,

D: y nadie lo comprendió,

D: ¿qué hace el ecologismo en un barrio tan de pijos?

K: Militarás con modelos que mi hija tenga celos,

K: Ganaremos elecciones,

K: morado y blanco son nuestros colores,

K: Somos la izda pija y revolucionaria,

K: la idea no es estrafalaria


D: De acuerdo, si has construido el edificio,

D: ¡haré el ecologismo!

* Poemas a Koro (XIII)

A Pablo le han vencido,

porque él mismo se ha ido,

hacia tí van todas las miradas,

eres vasca, rubia y guapa,



Amazon está cambiando,

necesito seguirlo observando.


Con amor puro y eterno,

no pretendo ser tu dueño,

solo el hombre de tus sueños.  



No es Belarra una lagarta,

acéptala que no maltrata,

que nos quita pederastas,

que piensa en la vivienda,

que no te hará ir a arrastras.



Pobre Irene, triste y sola,

queda en Moncloa,

con su amado 

en el paro.



Podrás hacerle algo de compañía,

sí, es ella buena chica.



Trabaja en el problema,

de género,

reducir la brecha.


Y, claro,

que su marido encontrará trabajo,

* Poemas a Koro (XIV)
Todos se querían reir
de que Koro
quiera a David.

Eso no sé si va a ser así,
pues todo el que se ría,
va a morir.

Y esta manera de morir,
lo llamaré COVID,
y en el 2019 va a ocurrir.

No des gracias,
os dirá David.

Veo el sufrimiento,
que no hayamos hecho el casamiento,
el volcan en la palma está ardiendo,
hay demasiados muertos.

* Poemas a Koro (XV)
Con lo del covid te has pasado,
todo el mundo está enmascarado,
el virus se ha propagado,
yo ya me he enfadado,
Koro, con tu madre me voy para otro lado.

A las residencias he llegado, 
la marea se ha creado,
con Pablo están cabreados,
con el PP malhumorados,
todo el mundo se ha manifestado.

* Poemas a Koro (XVI)
La ancianita decía,
no me reía,
solo jugaba mi partida.

Dijeron lo que no era,
solo veía la novela.

No entendí el error en ir al dominó,
era la hora, me lo dijo el reloj

Son las personas mayores,
quienes nos hicieron ver los errores,
pagaron justos, les llamaron pecadores.

* Poemas a Koro (XVII)

De herencia a herencia,
se consigue recompensa.

Corona virus funciona así,
si lo entiendes hay una parte para tí.

Solo queréis dinero,
el de los abuelos,
eso es no es amor verdadero.

Aunque no sea un nobel en economía, 
sé lo que está mal y bien en la vida

* Poemas a Koro (XVIII)

Sidharta me lo enseñó, 
el amor verdadero es iluminación.

Apliquemos la siguiente solución:
El gobierno de la chicas
mola mogollón,
acabamos con la brecha de género,
sin que nos cueste un riñón.

De Podemos o Socialistas,
en este país solo va a haber ministras.

Y el género de presidencia,
mujer y con paciencia.

Dictadura feminista,
para construir muchas familias

Que nadie se quede sin pareja, 
será decretado por ley
e implementado con ciencia

Hazme de tu familia,
haz que me case contigo,
con tu madre,
o con tu hija.

Todo a su momento,
lo primero tomar el parlamento,
entraré con mi marido,
mis escoltas con el armamento,
levantan las manos,
diputadas y diputados de Podemos,
cogen más armamento,
más diputados están apuntados.

Poner la Televisión,
el parlamento está tomado,
¡Koro Castellano es la nueva líder de Estado!

¡Viva el Pais Vasco!
¡Viva Koro Castellano!
¡Viva Ámazon!

* Poemas a Koro (XIX)

¿Y con la policía qué pasó?
¿Por qué no intervino el Ejército español?

Drones Amazon, los fulminó,

Yo te quiero, no tengas temor,
ahora hagamos el amor.

¿Por qué ves amor y no dominación?
Estoy asustado, sometido al control.

Así es el baile del amor,
conocimiento, cariño
y de los cuerpos atracción

Pues así obedezco,
si me dices que te quiera,
te quiero,
si me dices que me aleje,
me alejo,
si me cambias por un robot,
ni me sorprendo.

Entonces volvería a la situación anterior,
yo en Amazon,
y con mi marido y su parlamento español.

Te diré la verdad,
en el amor verdadero existe reciprocidad,
tiene algo que ver con eso de la igualdad.

¿No te valen mis muestras de afecto?
Por tí y por mí he hecho temblar al mundo entero.

Pero soy yo el que negar tu voluntad no puedo.

Me vale con tu ánimo, tus muestras de afecto,
me gustaría ser la jefa del mundo entero,
pero aún hay machismos eternos,
Bezos, Google, Twitter, Facebook, ...

Todos traman algo, así lo siento.
Puedes estar conmigo o irte con ellos.

No voy a recorrer el mundo entero,
para cambiar a otra dominación,
si dominas mi barrio,
dominas mi corazón.

Y eso es lo que quería expresarte yo.

* Poemas a Koro (XX)

La Casa de la Moneda
a Amazon interesaba,
el edificio ecologista no está por tí,
es por todo el que vivía en cualquier fachada.

La dominación vasca está terminada.

Con España tiranizada,
Irene será la primera en ser ejecutada.

Y así la tontería castellana,
queda cancelada.

El GAL estaba escondido,
hablaron los amigos,
en el parlamento hay guerra de cuchillos,

La dictadura se ha detenido.

¿Qué ha pasadon con los drones?

Dispararon unos aviones.

* Poemas a Koro (XXI)

Amazon ha puesto a la hija
al mando en España de la compañía,
otra idea, otro talante,
esa mujer no es arrogante,
viendo a sus padres en la carcel,
la juventud le quiere,
Castilla no le teme,
en Castilla, nace, crece y duerme,
en democracia escrupulosa,
ahora quedar volver a pensar las cosas.

Pedro ya retira,
del parlamento compañías,
la UE interviene,
algunos miedos, que todavía todos padecen.

David le habla un poquito,
con mi familia ocurrió lo mismo,
ilegales, cárcel, cuchillo,
mi hermano y sus amigos.

En el futuro quizás seamos amigos,
ahora, 
mejor no digas a nadie que nos conocimos.

* Poemas a Koro (XXII)

Al final todo es aburrido,
están en la cárcel
y éramos amigos.

No sé qué puedo hacer,
para volverles a ver...

Les llaman terroristas internacionales,
mucha policía,
son noticias oficiales.

A la hija hablarle no puedo,
siempre Amazon,
mucho revuelo.

Andy y Bezos,
descubrieron,
que sí que eran ellos,
y que era mucho dinero.

Ójala pudieran salir,
estar con amigos 
en una isla
donde no puedan delinquir

¡Cuba es algo así!

Por USA bloqueados,
siempre vigilados,
casi sin Internet,
en Amazon,
no se vuelven a meter.

Esa idea se va logrando,
víctimas y culpables,
a suramérica,
se irán marchando.

El doctorado lo termino
y quizás en el futuro,
haga turismo.

* Poemas a Koro (XXIII)

Y así termina COVID,
si lo has entendido,
hay una parte para tí.

* Poemas a Koro (XXIV)

D: Un par de años han pasado
D: Por fin, a Koro hija y a Laura he encontrado
D: En Amazon me invitan a una copa
HK: Es por mi madre
HK: de su sangre las últimas gotas
D: ¿Qué ha pasado? ¿Cómo ha sido?
HK: Todo Cuba ha ardido
L: Comunismo == Terrorismo
D: ¿Esta vez qué han hecho?
L: Camisetas de Fidel
L: El Ché y Ciemfuegos
D: Y a tí ¿qué te ha tocado?
HK: David, en España soy el supra Estado
HK: Yo mando a todos los mandos
HK: Si bien mi dinero no es infinito
HK: Tengo más que cualquier ministro
HK: banquero, especulador, o futbolisto
HK: Y AHORA DÍ
HK: ¿Quieres que las hijas de Satán que en su día no te DÍ?
D: ID a mí

Koro, Laura y yo tuvimos sexo y lujuria sin ternura
hasta ver un bebé en la cuna

HK: David ¿por qué lo has hecho?
HK: Soy rica
HK: No permitiré que un bebé robe mi derecho a techo
D: Ya he dejado el instinto satisfecho
D: Estoy más cuerdo
D: La biología me lleva a ello
D: Soy hetero
D: Ha sido un placer hacerlo
HK: Entiendo
HK: Al estar mejor el cuerpo
HK: Está mejor el cerebro
HK: David, el mundo está fatal
HK: COVID demuestra que el nuevo ser me va a matar
D: El capitalismo ha desnaturalizado
D: La relación familiar natural
D: Éramos tu y yo en realidad
D: Que quitamos cordura a tus aitas
D: Con eso de los afectos de la sociedad
D: Pensemos cómo queremos la nueva sociedad
D: Ya a cualquiera la idea le podemos cambiar

* Poemas a Koro (XXV)

HK: David me van gustando las vacaciones
HK: Haz que me ilusione
HK: Te miro el CV
HK: ¿Qué me propones?
D: El corona ha hecho daño al socialismo
D: pero arreglamos los hijos
D: la socialdemocracia está dañada
D: de ahí se puede hacer batalla
HK: Ya te callas
HK: Gano a Torvalds y a la CRUE
HK: Y a un montón de empresas canallas
HK: Estate aquí contratado
HK: Te basta con hacer el vago

* Poemas a Koro (XXVI)

UyK: No, nos hemos matado
UyK: Salimos de la isla a nado
HK: Jolín, ya era victoriosa 
HK: ¿vais a volver a decir que soy idiota?
UyK: Volvéis a la militancia
UyK: Tus amigos te acompañan
UyK: Y quitarles cualquier rastro
UyK: De que fueron empresarios
HK: Jolín, ahora dejo de ser rica
HK: Es por contratar al padre de mi hija
D: Son los abuelos
D: Nos ayudan con los nietos
D: Es mejor que no estén muertos
HK: Pero ahora ¿Qué hacemos?
HK: Estamos sin dinero
D: Por eso tenemos a Laura
D: Para que nos explique cómo ganar dinero con la militancia
L: A trabajar en la ONG
L: algo habrá que hacer
L: yo la dirigiré
L: vosotros podéis repartir panfletos
L: da algo de dinero
D: con personas de valores
D: más felices
D: mejores ecuaciones
HK: Nos quedamos sin casa
HK: Y sin coche
HK: Los bebés lloran sin los postres
D: Viviremos de alquiler
D: en una casa los tres
D: con los yayos los bebés

* Poemas a Koro (XXVII)

HK: David no te quiero
HK: te odio
HK: a tí y a este matrimonio

D: Esa idea no es ninguna maravilla ....
D: ¡Es el fin de las ideologías!
D: Llámalo comunismo o anarquía
D: Sin tu amor todo ardería

HK: Sí ...
HK: Pues aquí tienes la cerilla

D: FRAVM, Centros Sociales
D: Colectivos Antinucleares
D: Sindicatos militantes
D: Colectivos homosexuales
D: Que quede todo destruido
D: Que gane un solo partido
D: Quien defienda a Adam Smith con tino
D: Lo demás es todo un timo

D: Agotabas mi amor
D: Siempre con rencor
D: Hacia mí
D: Contra tu familia
D: Hacia todos los que te querían

D: Stop al pensamiento positivo
D: Aprende tu a escribir algoritmos
D: Amazon es un monopolio malvado
D: A todos nos tiene subyugados
D: A mí no me vuelves a timar
D: Con libre mercado nos vamos a sincerar

* Poemas a Koro (XXVIII)

L: ¿Quiénes son esos?
D: ¡mendigos!
L: A Koro la han cogido
L: en un coche la han metido
L: hay que hablar con el partido
D: Sí, lo he entendido

* Poemas a Koro (XXIX)

K: Pensé que alguien me había cogido
K: pero eran mi esposa y mi marido
L: Estamos en Baztán
L: A tus padres les interesó el plan
D: Es tu fiesta de cumpleaños
D: Aunque todo resulta extraño
KyU: Estamos en una okupa abertzale
KyU: Desde aquí nos gusta liderar
D: Así es la empresa de Andí
D: Y+D+I 
D: Si lo sabes entender
D: hay una parte para tí

* Poemas a Koro (XXX)

KLU: David me dejo de hacer la lista
KLU: sois de la Unión Real de la Juventud Comunista
KLU: ya tienes tus hijas
KLU: te las habíamos robados desde Euskal Herría
KLU: la vacuna está fuertecita
KLU: Andi tiene la compañía
KLU: vuelves con la inesita

* Poemas a Koro (XXXI)

Fiesta, baile, risas y regalos, ahora, por fin,
todos parecen humanos,
pero espera ...

KLU: D verdadera con I verdadera
KLU: juntaré todas las letras
KLU: hasta que madre pierda
D: en eso puedo ayudar
D: he escrito el software para hacer los match
D: en la UNED están llamando
D: quieren ofrecerme un contrato
L: con un Unidas Podemos he hablado
L: las ministras también han ayudado
KLU: Así sí me siento tu amiga
KLU: Soy Ko-RRo, la Ro Kooperativa
D: Ese será el nombre de la nueva compañía

* Poemas a Koro (XXXII)

I: Cambiando valores a Baztán hacéis daño
I: aquí cada cual están siempre en un lado
I: con ustedes no entendemos
I: si sois del monopolio o de Unidas Podemos
I: Así, que de nada de ustedes creemos
I: Queremos veros unos años igual
I: Si no no os vamos a aceptar
I: Bastantes problemas tuvimos
I: Con Marina D'Or y esa maldita ecuación
D: Con menos cambio extremista
D: Se tranquilizaría la economía
D: Lo vamos a sopesar
D: Está bien dejar de cambiar
I: Ahora fuera de Baztán
I: Aquí todavía no debéis pasar

* Poemas a Koro (XXXIII)

KLU: Vaya un lío hemos armado
KLU: Familia y trabajo se han desajustado
KLU: Contigo no sé qué hacer
KLU: Quizás te deba vender
KLU: Te exporto a Suramérica
K: Allí Amazon no tiene mucha presencia ...

* Poemas a Koro (XXXIV)

D: Conocí a cierta mujer aterrizando
D: Eres la diosa que quiero, que adoro,
D: que por su cuerpo me hace suspirar de todos modos,
D: casi no conozco 
D: y destruye homosexuales y terroristas
D: que vienen contra mí gracias a su coño,
D: científicos, sectas y forbesianos,
D: a todos les para conmigo follando
D: jamás vi un mayor poder clitoriano

D: Que la declaren diosa todavía
D: no es mi estrategia,
D: primero que la declaren reina,
D: ser yo su rey y que el mundo comprenda,
D: que hemos llegado a una nueva época,
D: juego de tronos es ahora de izquierdas
D: la monarquía sexual 
D: en toda Suramérica va a triunfar,
D: reyes y reinas es la estrategia hetero perfecta

D: Ya en el espacio que Munsk lo comprenda
D: que esta mujer es capaz de mover los planetas,
D: las estrellas, constelaciones perfectas

D: Me imagino que me acerco a ese cuerpo despacio,
D: retiro su pelo con mi mano, beso suavemente sus labios,
D: siguen mis besos por su cuello recorren todo el cuerpo,
D: les acompañan mis dedos que llevan de las flores los pétalos,
D: bailamos lambada hasta llegar a la cama
D: y tener orgasmos toda la semana

* Poemacs a Koro (II)

D: Me sentí libre más de un día
D: de las horribles pesadillas
D: luego desapareció cual dulce dama

La Inter de Paul le saluda

IP: Bienvenido comandante
IP: Queremos interrogarle
IP: Hemos escuchado las conversaciones
IP: Queremos analizar orina y sangre
IP: Que sople fuerte el aire
D: De acuerdo, adelante
IP: Todo limpio y estamos sorprendidísimos
IP: Espere un momentito
IP: Es este ficherito
IP: all.csv se hace llamar
IP: Este fichero es ilegal
D: Ponía MIT, lo juro
IP: Licencia no había
IP: se había llamado a la policía
IP: Hay muchos casos así
IP: La conducta suicida es sí
IP: leemos el setup.py
IP: sin buscar el fichero MIT
IP: si su vida quiere salvar
IP: lo tiene que eliminar
IP: su actitud es insana
IP: queremos para usted un mañana

* Poemacs a Koro (III)

D: Hemos acordado
D: que en la Free Software Directory
D: nos juntamos
D: entre todos nos miramos
D: si en la licencia somos
D: buenos o malos

D: Ahora queremos cumplir
D: tenemos ganas de vivir

D: La sustancia psicológica ilegal
D: se aleja de mi psicología natural

D: Santamaría aléjate
D: tu all.csv no lo quiero tener

* Poemas a Koro (XXXV)

D: Y así estos poemas han acabado
D: porque ya no hablábamos
D: de Koro Castellano

* Poemas a Koro (XXXVI)

K: Espera roquero
K: dinos que es
K: amor verdadero
K: ¿amor al dinero?
KLU: amor a la descendencia
KLU: amor a tener un techo
I: el primer amor
I: el amor eterno
La: a los valores me debo
La: eso es lo verdadero
Lu: solo es sincero
Lu: el sexo del momento

D: amor a mi propia vida
D: eso lo primero
D: después sí, todo eso
D: algo de dinero
D: de sexo
D: y que haya un techo
D: Maslow debe estar satisfecho

D: Luego más amigas y amigos
D: y más dinero
D: constancia en los valores
D: dan eso
D: más amistades y dinero

D: con más gente a favor de gente
D: más amistad, más inteligente
D: familia, hijos, dinero,
D: la felicidad que no miente

* Poemas a Koro (XXXVII)

D: el tiempo pasa deprisa,
D: David trabaja la ingeniería,
D: con su nueva amiga,
D: love programming,
D: es la nueva metodología,
D: entender afectos, ideología,
D: sexo, amistades, empatías,
D: objetivos, economías,
D: se emparejan programadoras,
D: y programadores con simpatía,
D: De Bolivía a Ecuador,
D: no hay lugar para el rencor,
D: todo es psicología y educación,
D: en un continente hecho para el amor.

* Licencia 
Este documento está bajo una [[http://creativecommons.org/licenses/by-nc-nd/3.0/es/deed.es][Licencia Creative Commons
Reconocimiento-NoComercial-SinObraDerivada 3.0]]

[[http://creativecommons.org/licenses/by-nc-nd/3.0/es/deed.es][file:http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png]]


