#+TITLE: Versos escondidos a Koro Castellano. No hay nada más fuerte que el amor verdadero
#+LANGUAGE: es
#+AUTHOR: David Arroyo Menéndez
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/org.css" />
#+BABEL: :results output :session

[[http://www.davidam.com][Come back to davidam.com]]

Esta historia es pura ficción, cualquier parecido con la realidad es
pura coincidencia.

* Poemas a Koro (I)
Le veo liderar

con Amazon azul oscuro y

la sonrisa del dorado

y así mi corazón corre alocado


Deme una oportunidad

para construir

Amazon Universidad


Que salgan doctorandos

con doctoras, con doctores,

con liderazgo universal,

nadie se va a enfadar.


Yo a usted le quiero ...

ayudar ...

Pero me dan miedo

quienes no le quieren ná

...

* Poemas a Koro (II)
Ví a Andi

y dí

¿Encontrará la verdadera D

a la verdadera Í?

Id,

Calla cadete,

únete a KDE.

Dime

¿Qué?

Yo soy de unir.

* Poemas a Koro (III)

Libros, libros y más libros

Y al final todos los contenidos,

música, vídeos,

dvds de mil amores,

ordenadores,

no son difamaciones,

son obras de trabajadoras y trabajadores

* Poemas a Koro (IV)

Una mujer, un objetivo,

liderazgo internacional,

tiene sentido,

valores, economía,

ecuaciones,

fotos, simpatía,

razones.

Una distribución para todas las organizaciones

* Poemas a Koro (V)

¿Enamorado?

Y motivado!

Aquí se trabaja,

No nos gusta estar parados,

Pensamiento divertido,

Sonrientes, cayendo bien a la gente,

No nos vamos a cansar,

Estamos para triunfar

* Poemas a Koro (VI)

¿Qué me dirá si le digo libros libres?

Proponga, plantee, 

Encontraremos la ecuación que más conviene,

Sopesamos gastos e ingresos,

Planteamos buenos precios.

* Poemas a Koro (VII)

¿Es este un sueño norteamericano?

Queremos ganar en todos los mercados,

España, Japón, Korea,

pero también China o Guinea,


Déjame que te seduzca,

hazlo rentable,

que se reproduzca.

* Poemas a Koro (VIII)

Una mujer que es un monumento,

con el corazón en el parlamento,

en su familia,

en los buenos sentimientos,

¿Qué más queremos?


¡Koro Castellano!

una mujer de cuento.


* Poemas a Koro (IX)

Koro te encuentro en Vogue

y en la prensa,

pero no en la Wikipedia


¡Será que no interesa!


No amas ese debate,

Ni esa protesta.

Te enseñaría a una 

que sí te besa.


Y a mas de una y a más de dos

que cuando te hablo,

siento que hablo cerca de Dios.

* Poemas a Koro (X)

A Koro todos le van a querer,

nadie me va a convencer contra usted,

el lechero, el político,

el vecino que habla de usted,

Yo sí le sé querer,

Nadie nos debe ofender



¿Y esos de todostuslibros?,

libreros unidos, con ánimo de victimismo,

traficantes de un mundo desaparecido,

Amazon ha vencido,

Ellas y ellos han sonreido.



¿Es lulu.com una revolución?

Nos sirve para un revolcón,

Idea locuaz la de la libertad,

Nosotros la podríamos comercializar,

liderar, mejorar y ampliar,

hágame el amor, pero de verdad

* Poemas a Koro (XI)
Sé que tenemos un sueño escondido,

el del ecofeminismo,

es porque tuvimos corazoncito,

no nos estorba, así nos damos más amorcito,

alegría, confianza inversora,

sí, me gusta tratarle como a una gran señora.

* Poemas a Koro (XII)
Estaba en mi balcón y vaya un follón,

verde paz apareció,

y nadie lo comprendió,

¿qué hace el ecologismo en un barrio tan de pijos?

Militarás con modelos que mi hija tenga celos,

Ganaremos elecciones,

morado y blanco son nuestros colores,

Somos la izda pija y revolucionaria,

la idea no es estrafalaria


De acuerdo, si has construido el edificio,

¡haré el ecologismo!

* Poemas a Koro (XIII)
A Pablo le han vencido,

porque él mismo se ha ido,

hacia tí van todas las miradas,

eres vasca, rubia y guapa,



Amazon está cambiando,

necesito seguirlo observando.


Con amor puro y eterno,

no pretendo ser tu dueño,

solo el hombre de tus sueños.  



No es Belarra una lagarta,

acéptala que no maltrata,

que nos quita pederastas,

que piensa en la vivienda,

que no te hará ir a arrastras.



Pobre Irene, triste y sola,

queda en Moncloa,

con su amado 

en el paro.



Podrás hacerle algo de compañía,

sí, es ella buena chica.



Trabaja en el problema,

de género,

reducir la brecha.


Y, claro,

que su marido encontrará trabajo,

* Poemas a Koro (XIV)
Todos se querían reir
de que Koro
quiera a David.

Eso no sé si va a ser así,
pues todo el que se ría,
va a morir.

Y esta manera de morir,
lo llamaré COVID,
y en el 2019 va a ocurrir.

No des gracias,
os dirá David.

Veo el sufrimiento,
que no hayamos hecho el casamiento,
el volcan en la palma está ardiendo,
hay demasiados muertos.

* Poemas a Koro (XV)
Con lo del covid te has pasado,
todo el mundo está enmascarado,
el virus se ha propagado,
yo ya me he enfadado,
Koro, con tu madre me voy para otro lado.

A las residencias he llegado, 
la marea se ha creado,
con Pablo están cabreados,
con el PP malhumorados,
todo el mundo se ha manifestado.

* Poemas a Koro (XVI)
La ancianita decía,
no me reía,
solo jugaba mi partida.

Dijeron lo que no era,
solo veía la novela.

No entendí el error en ir al dominó,
era la hora, me lo dijo el reloj

Son las personas mayores,
quienes nos hicieron ver los errores,
pagaron justos, les llamaron pecadores.

* Poemas a Koro (XVII)

De herencia a herencia,
se consigue recompensa.

Corona virus funciona así,
si lo entiendes hay una parte para tí.

Solo queréis dinero,
el de los abuelos,
eso es no es amor verdadero.

Aunque no sea un nobel en economía, 
sé lo que está mal y bien en la vida

* Poemas a Koro (XVIII)

Sidharta me lo enseñó, 
el amor verdadero es iluminación.

Apliquemos la siguiente solución:
El gobierno de la chicas
mola mogollón,
acabamos con la brecha de género,
sin que nos cueste un riñón.

De Podemos o Socialistas,
en este país solo va a haber ministras.

Y el género de presidencia,
mujer y con paciencia.

Dictadura feminista,
para construir muchas familias

Que nadie se quede sin pareja, 
será decretado por ley
e implementado con ciencia

Hazme de tu familia,
haz que me case contigo,
con tu madre,
o con tu hija.

Todo a su momento,
lo primero tomar el parlamento,
entraré con mi marido,
mis escoltas con el armamento,
levantan las manos,
diputadas y diputados de Podemos,
cogen más armamento,
más diputados están apuntados.

Poner la Televisión,
el parlamento está tomado,
¡Koro Castellano es la nueva líder de Estado!

¡Viva el Pais Vasco!
¡Viva Koro Castellano!
¡Viva Ámazon!

* Poemas a Koro (XIX)

¿Y con la policía qué pasó?
¿Por qué no intervino el Ejército español?

Drones Amazon, los fulminó,

Yo te quiero, no tengas temor,
ahora hagamos el amor.

¿Por qué ves amor y no dominación?
Estoy asustado, sometido al control.

Así es el baile del amor,
conocimiento, cariño
y de los cuerpos atracción

Pues así obedezco,
si me dices que te quiera,
te quiero,
si me dices que me aleje,
me alejo,
si me cambias por un robot,
ni me sorprendo.

Entonces volvería a la situación anterior,
yo en Amazon,
y con mi marido y su parlamento español.

Te diré la verdad,
en el amor verdadero existe reciprocidad,
tiene algo que ver con eso de la igualdad.

¿No te valen mis muestras de afecto?
Por tí y por mí he hecho temblar al mundo entero.

Pero soy yo el que negar tu voluntad no puedo.

Me vale con tu ánimo, tus muestras de afecto,
me gustaría ser la jefa del mundo entero,
pero aún hay machismos eternos,
Bezos, Google, Twitter, Facebook, ...

Todos traman algo, así lo siento.
Puedes estar conmigo o irte con ellos.

No voy a recorrer el mundo entero,
para cambiar a otra dominación,
si dominas mi barrio,
dominas mi corazón.

Y eso es lo que quería expresarte yo.

* Licencia 
Este documento está bajo una [[http://creativecommons.org/licenses/by-nc-nd/3.0/es/deed.es][Licencia Creative Commons
Reconocimiento-NoComercial-SinObraDerivada 3.0]]

[[http://creativecommons.org/licenses/by-nc-nd/3.0/es/deed.es][file:http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png]]
