* Poemas a Koro (I)
Le veo liderar
con Amazon azul oscuro y
la sonrisa del dorado
y así mi corazón corre alocado

Deme una oportunidad
para construir
Amazon Universidad

Que salgan doctorandos
con doctoras, con doctores,
con liderazgo universal,
nadie se va a enfadar.

Yo a usted le quiero ...
ayudar ...
Pero me dan miedo
quienes no le quieren ná
...

* Poemas a Koro (II)
Ví a Andi
y dí
¿Encontrará la verdadera D
a la verdadera Í?
Id,
Calla cadete,
únete a KDE.
Dime
¿Qué?
Yo soy de unir.

* Poemas a Koro (III)
Libros, libros y más libros
Y al final todos los contenidos,
música, vídeos,
dvds de mil amores,
ordenadores,
no son difamaciones,
son obras de trabajadoras y trabajadores

* Poemas a Koro (IV)
Una mujer, un objetivo,
liderazgo internacional,
tiene sentido,
valores, economía,
ecuaciones,
fotos, simpatía,
razones.

Una distribución para todas las organizaciones

* Poemas a Koro (V)
¿Enamorado?
Y motivado!
Aquí se trabaja,
No nos gusta estar parados,
Pensamiento divertido,
Sonrientes, cayendo bien a la gente,
No nos vamos a cansar,
Estamos para triunfar

* Poemas a Koro (VI)
¿Qué me dirá si le digo libros libres?
Proponga, plantee, 
Encontraremos la ecuación que más conviene,
Sopesamos gastos e ingresos,
Planteamos buenos precios.

* Poemas a Koro (VII)

¿Es este un sueño norteamericano?
Queremos ganar en todos los mercados,
España, Japón, Korea,
pero también China o Guinea,

Déjame que te seduzca,
hazlo rentable,
que se reproduzca.

* Poemas a Koro (VIII)

Una mujer que es un monumento,
con el corazón en el parlamento,
en su familia,
en los buenos sentimientos,
¿Qué más queremos?

¡Koro Castellano!
una mujer de cuento.

* Poemas a Koro (XIX)

Koro te encuentro en Vogue
y en la prensa,
pero no en la Wikipedia

¡Será que no interesa!

No amas ese debate,
Ni esa protesta.

Te enseñaría a una 
que sí te besa.

Y a mas de una y a más de dos
que cuando te hablo,
siento que hablo cerca de Dios.

* Poemas a Koro (XX)
A Koro todos le van a querer,
nadie me va a convencer contra usted,
el lechero, el político,
el vecino que habla de usted,
Yo sí le sé querer,
Nadie nos debe ofender

¿Y esos de todostuslibros?,
libreros unidos, con ánimo de victimismo,
traficantes de un mundo desaparecido,
Amazon ha vencido,
Ellas y ellos han sonreido.

¿Es lulu.com una revolución?
Nos sirve para un revolcón,
Idea locuaz la de la libertad,
Nosotros la podríamos comercializar,
liderar, mejorar y ampliar,
hágame el amor, pero de verdad

* Poemas a Koro (XXI)
Sé que tenemos un sueño escondido,
el del ecofeminismo,
es porque tuvimos corazoncito,
no nos estorba, así nos damos más amorcito,
alegría, confianza inversora,
sí, me gusta tratarle como a una gran señora.

* Poemas a Koro (XXII)
Estaba en mi balcón y vaya un follón,
verde paz apareció,
y nadie lo comprendió,
¿qué hace el ecologismo en un barrio tan de pijos?
Militarás con modelos que mi hija tenga celos,
Ganaremos elecciones,
morado y blanco son nuestros colores,
Somos la izda pija y revolucionaria,
la idea no es estrafalaria
