#+TITLE: Sobre el Amor y el Poder
#+LANGUAGE: es
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/org.css" />
#+AUTHOR: David Arroyo Menéndez

[[http://www.davidam.com][Volver a davidam.com]]

Ya Erich Fromm hizo las distinciones sobre los distintos tipos de
amor: amistad, amor familiar, amor de pareja, ... Hoy quiero contar mi
reflexión personal sobre qué ocurre en el amor desde mi propia
experiencia.

Empezar a amar es sentirte a gusto con la persona que se tiene cerca,
esto puede ser por muchos motivos, quizás por un tema de valores,
conocimientos, trabajo técnico común, roce físico, experiencias
vividas, etc. Este empezar a amar puede derivar en amistad, o en
pasión, muchas veces depende de lo que las personas llaman la chispa
del amor (el beso, el sexo, etc.). Desde ese empezar a amar hay veces
que se va en un sentido o en otro, si se va durante bastante tiempo en
el sentido de acercarse a los valores, a los conocimientos, al roce,
etc. y luego nunca llega la chispa pues a muchas personas les provoca
frustración y si se va a otra persona con inversiones diferentes pues
se puede considerar robo, de la misma manera que te quiten un
ordenador, o una mesa, u otro objeto físico.

De esta manera, el amor verdadero se podría considerar el respetar la
inversión de la persona que se tiene cerca sin hacer robo o
frustración. Esto no siempre es fácil, pero es importante ser
respetuoso. Lo que pasa con el amor es que esto no se puede
cuantificar, ni es fácil decir que la otra persona esté realmente
invertiendo a nivel de manera consciente o inconsciente en la otra
persona. Invertir en lo mismo que la otra persona y no amarla es raro.

Hay políticos que antes de hundir a una persona lo que hacen es
invertir mucho en sus valores, o trabajo técnico para robarle todos
sus lazos afectivos. Otros lo que hacen es despretigiar a la persona a
través de sus lazos. Otros les meten miedos para que no se acerquen a
la gente que realmente les quiere. Otros te dan mucho amor para
sugestionarte a que pierdas cosas materiales como puesto de trabajo, o
pertenencias. En general, lo que los políticos quieren es robar amor o
dinero para conseguir cargos. Los medios de comunicación también
juegan con los sentimientos para conseguir el amor que interesa a la
clase dirigente, de este modo, el tema de los sentimientos está
siempre muy manipulado al interés de los políticos y la gente que te
rodea y la creencia en el amor verdadero es complicada. Hay mucha
gente que invierte en valores y trabajo similar al tuyo y puede haber
muchos amores razonables y la gente se puede sentir enamorada durante
un tiempo y luego cambiar ese sentimiento hacia el odio o incluso
hacia la indiferencia.

El truco para enfrentarse a los robos de amor de los políticos y
otros/as ladronzuelos/as es exigirle en todo momento cosas materiales,
dar pocos datos, no caer en sugestiones/mentiras oficiales o no y
tenerlo todo bien firmado, porque todos los políticos son ladrones de
amor para ascender en cargos, o conseguir dinero real, a veces,
incluso los que se hacen llamar anarcosindicalistas (porque amigos en
el anarcosindicalismo hay militantes y secretarios/as y eso es un es
un cargo político), o cooperativistas (hay cooperativas con jefes/as y
asaliariados/as). Pero evidentemente, dónde más se roba es en la
política de partidos.

Otra protección frente a los robos de amor es amar a personas que
tienen un nivel de poder similar al tuyo, con valores son similares a
los tuyos y que cambian sus sentimientos amorosos a una velocidad
similar a la tuya.

Esta página está bajo una [[http://creativecommons.org/licenses/by-nd/3.0/es/deed.es][Licencia Creative Commons
Atribución-SinDerivadas 3.0]].
