#+TITLE: Testing Licenses
#+LANGUAGE: es
#+AUTHOR: David Arroyo Menéndez
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/org.css" />
#+BABEL: :results output :session
  
[[http://www.davidam.com][Volver a davidam.com]]

* Licencia
Copyright (C)  2013 David
    Se permite copiar, distribuir y/o modificar este documento
    bajo los términos de la GNU Free Documentation License, Version 1.3
    o cualquier versión publicada por la Free Software Foundation;
    sin Secciones Invariantes y sin Textos de Portada o Contraportada.
    Una copia de la licencia está incluida en [[https://www.gnu.org/copyleft/fdl.html][GNU Free Documentation License]].

[[https://www.gnu.org/copyleft/fdl.html][file:https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/GFDL_Logo.svg/200px-GFDL_Logo.svg.png]]
* License
Copyright (C)  2013 David
    Permission is granted to copy, distribute and/or modify this document
    under the terms of the GNU Free Documentation License, Version 1.3
    or any later version published by the Free Software Foundation;
    with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
    A copy of the license is included in [[https://www.gnu.org/copyleft/fdl.html][GNU Free Documentation License]].

[[https://www.gnu.org/copyleft/fdl.html][file:https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/GFDL_Logo.svg/200px-GFDL_Logo.svg.png]]
* Licença
Este texto é disponibilizado nos termos da licença [[https://creativecommons.org/licenses/by-sa/3.0/br/deed.pt_BR][Atribuição 3.0 Brasil]]

[[https://creativecommons.org/licenses/by-sa/3.0/br/deed.pt_BR][file:http://i.creativecommons.org/l/by/3.0/80x15.png]]
* Licència
El text està disponible sota la [[https://creativecommons.org/licenses/by-sa/3.0/es/deed.ca][Reconeixement 3.0 Espanya]]

[[https://creativecommons.org/licenses/by-sa/3.0/es/deed.ca][file:http://i.creativecommons.org/l/by/3.0/80x15.png]]
* Lizenz
Dieses Werk bzw. Inhalt steht unter einer [[https://creativecommons.org/licenses/by-sa/3.0/de/deed.de][Lizenz Creative Commons Namensnennung 3.0 Deutschland]]

[[https://creativecommons.org/licenses/by-sa/3.0/de/deed.de][file:http://i.creativecommons.org/l/by/3.0/80x15.png]]
* Licencia
Este documento está bajo una [[http://creativecommons.org/licenses/by/3.0/es/deed.es][Licencia Creative Commons Atribución 3.0 España]]

[[http://creativecommons.org/licenses/by/3.0/es/deed.es][file:http://i.creativecommons.org/l/by/3.0/80x15.png]]
* License
This document is under a [[http://creativecommons.org/licenses/by/3.0/es/deed.es][Creative Commons Attribution 3.0]]

[[http://creativecommons.org/licenses/by/3.0/es/deed.es][file:http://i.creativecommons.org/l/by/3.0/80x15.png]]
* Licenco
Ĉi tiu verko estas disponebla laŭ la permesilo [[http://creativecommons.org/licenses/by/3.0/eo/deed.eo][Krea Komunaĵo Atribuite 3.0 Neadaptita]]

[[http://creativecommons.org/licenses/by/3.0/eo/deed.eo][file:http://i.creativecommons.org/l/by/3.0/80x15.png]]
* Licenzua
Testua [[http://creativecommons.org/licenses/by/3.0/es/deed.eu][Aitortu 3.0 Espainia]] lizentziari jarraituz erabil daiteke

[[http://creativecommons.org/licenses/by/3.0/es/deed.eu][file:http://i.creativecommons.org/l/by/3.0/80x15.png]]
* Lisenssi
Teksti on saatavilla [[http://creativecommons.org/licenses/by/1.0/fi/deed.fi][Nimeä 1.0 Suomi]] lisenssillä

[[http://creativecommons.org/licenses/by/1.0/fi/deed.fi][file:http://i.creativecommons.org/l/by/3.0/80x15.png]]
* Licence
Ce(tte) œuvre est mise à disposition selon les termes de la [[http://creativecommons.org/licenses/by/3.0/fr/deed.fr][Licence Creative Commons Attribution 3.0 France]]

[[http://creativecommons.org/licenses/by/3.0/fr/deed.fr][file:http://i.creativecommons.org/l/by/3.0/80x15.png]]
* Licenza
Todo o texto está dispoñible baixo a [[http://creativecommons.org/licenses/by/3.0/es/deed.gl][licenza Creative Commons recoñecemento compartir igual 3.0]].

[[http://creativecommons.org/licenses/by/3.0/es/deed.gl][file:http://i.creativecommons.org/l/by/3.0/80x15.png]]
* Licenza
Quest'opera e distribuita con Licenza [[http://creativecommons.org/licenses/by/3.0/it/deed.it][Licenza Creative Commons Attribuzione 3.0 Italia]]

[[http://creativecommons.org/licenses/by/3.0/it/deed.it][file:http://i.creativecommons.org/l/by/3.0/80x15.png]]
* Licença
Este texto é disponibilizado nos termos da licença [[http://creativecommons.org/licenses/by/3.0/pt/deed.pt][Atribuição 3.0 Portugal]]

[[http://creativecommons.org/licenses/by/3.0/pt/deed.pt][file:http://i.creativecommons.org/l/by/3.0/80x15.png]]
* Licença
Este texto é disponibilizado nos termos da licença [[https://creativecommons.org/licenses/by-sa/3.0/br/deed.pt_BR][Atribuição Compartil ha Igual 3.0 Brasil]]

[[https://creativecommons.org/licenses/by-sa/3.0/br/deed.pt_BR][file:http://i.creativecommons.org/l/by-sa/3.0/80x15.png]]
* Licència
El text està disponible sota la [[http://creativecommons.org/licenses/by-sa/3.0/es/deed.ca][Reconeixement-CompartirIgual 3.0 Espanya]]

[[http://creativecommons.org/licenses/by-sa/3.0/es/deed.ca][file:http://i.creativecommons.org/l/by-sa/3.0/80x15.png]]
* Lizenz
Dieses Werk bzw. Inhalt steht unter einer [[http://creativecommons.org/licenses/by-sa/3.0/de/deed.de][Namensnennung - Weitergabe unter gleichen Bedingungen 3.0 Deutschland]]

[[http://creativecommons.org/licenses/by-sa/3.0/de/deed.de][file:http://i.creativecommons.org/l/by-sa/3.0/80x15.png]]
* Licencia
Este documento está bajo una [[http://creativecommons.org/licenses/by-sa/3.0/es/deed.es][Licencia Creative Commons Atribución Compartir por Igual 3.0 España]]

[[http://creativecommons.org/licenses/by-sa/3.0/es/deed.es][file:http://i.creativecommons.org/l/by-sa/3.0/80x15.png]]
* License
This document is under a [[http://creativecommons.org/licenses/by-sa/3.0/deed][License Creative Commons Attribution-ShareAlike Unported 3.0]]

[[http://creativecommons.org/licenses/by-sa/3.0/deed][file:http://i.creativecommons.org/l/by-sa/3.0/80x15.png]]
* Licenzua
Testua [[http://creativecommons.org/licenses/by-sa/3.0/es/deed.eu][Aitortu-PartekatuBerdin 3.0 Espainia]] lizentziari jarraituz erabil daiteke

[[http://creativecommons.org/licenses/by-sa/3.0/es/deed.eu][file:http://i.creativecommons.org/l/by-sa/3.0/80x15.png]]
* Lisenssi
Teksti on saatavilla [[http://creativecommons.org/licenses/by-sa/1.0/fi/deed.fi][Nimeä-JaaSamoin 1.0 Suomi]] lisenssillä

[[http://creativecommons.org/licenses/by-sa/1.0/fi/deed.fi][file:http://i.creativecommons.org/l/by-sa/3.0/80x15.png]]
* Licence
Ce(tte) œuvre est mise à disposition selon les termes de la [[http://creativecommons.org/licenses/by-sa/3.0/fr/deed.fr][Licence Creative Commons Attribution - Partage dans les Mêmes Conditions 3.0 France]]

[[http://creativecommons.org/licenses/by-sa/3.0/fr/deed.fr][file:http://i.creativecommons.org/l/by-sa/3.0/80x15.png]]
* Licenza
Todo o texto está dispoñible baixo a [[http://creativecommons.org/licenses/by-sa/3.0/es/deed.gl][licenza Creative Commons recoñecemento compartir igual 3.0]].

[[http://creativecommons.org/licenses/by-sa/3.0/es/deed.gl][file:http://i.creativecommons.org/l/by-sa/3.0/80x15.png]]
* Licenza
Quest'opera e distribuita con Licenza [[http://creativecommons.org/licenses/by-sa/3.0/it/deed.it][Licenza Creative Commons Attribuzione - Condividi allo stesso modo 3.0 Italia]]

[[http://creativecommons.org/licenses/by-sa/3.0/it/deed.it][file:http://i.creativecommons.org/l/by-sa/3.0/80x15.png]]
* Licença
Este texto é disponibilizado nos termos da licença [[http://creativecommons.org/licenses/by-sa/3.0/pt/deed.pt][Atribuição-CompartilhaIgual 3.0 Portugal]]

[[http://creativecommons.org/licenses/by-sa/3.0/pt/deed.pt][file:http://i.creativecommons.org/l/by-sa/3.0/80x15.png]]
* Licença
Este texto é disponibilizado nos termos da licença [[https://creativecommons.org/licenses/by-nd/3.0/br/deed.pt_BR][Atribuição Compartil ha Igual 3.0 Brasil]]

[[https://creativecommons.org/licenses/by-nd/3.0/br/deed.pt_BR][file:http://i.creativecommons.org/l/by-nd/3.0/80x15.png]]
* Licència
El text està disponible sota la [[http://creativecommons.org/licenses/by-nd/3.0/es/deed.ca][Reconeixement-SenseObraDerivada 3.0 Espanya]]

[[http://creativecommons.org/licenses/by-nd/3.0/es/deed.ca][file:http://i.creativecommons.org/l/by-nd/3.0/80x15.png]]
* Lizenz
Dieses Werk bzw. Inhalt steht unter einer [[http://creativecommons.org/licenses/by-nd/3.0/de/deed.de][Namensnennung-Keine Bearbeitung 3.0 Deutschland]]

[[http://creativecommons.org/licenses/by-nd/3.0/de/deed.de][file:http://i.creativecommons.org/l/by-nd/3.0/80x15.png]]
* Licencia
Este documento está bajo una [[http://creativecommons.org/licenses/by-nd/3.0/es/deed.es][Licencia Creative Commons Atribución-SinDerivadas 3.0]]

[[http://creativecommons.org/licenses/by-nd/3.0/es/deed.es][file:http://i.creativecommons.org/l/by-nd/3.0/80x15.png]]
* License
This document is under a [[http://creativecommons.org/licenses/by-nd/3.0/deed][Creative Commons Reconocimiento Unported 3.0]]

[[http://creativecommons.org/licenses/by-nd/3.0/deed][file:http://i.creativecommons.org/l/by-nd/3.0/80x15.png]]
* Licenzua
Testua [[http://creativecommons.org/licenses/by-sa/3.0/es/deed.eu][Aitortu-LanEratorririkGabe 3.0 Espainia]] lizentziari jarraituz erabil daiteke

[[http://creativecommons.org/licenses/by-sa/3.0/es/deed.eu][file:http://i.creativecommons.org/l/by-nd/3.0/80x15.png]]
* Lisenssi
Teksti on saatavilla [[http://creativecommons.org/licenses/by-sa/1.0/fi/deed.fi][Nimeä-JaaSamoin 1.0 Suomi]] lisenssillä

[[http://creativecommons.org/licenses/by-sa/1.0/fi/deed.fi][file:http://i.creativecommons.org/l/by-nd/3.0/80x15.png]]
* Licence
Ce(tte) œuvre est mise à disposition selon les termes de la [[http://creativecommons.org/licenses/by-nd/3.0/fr/deed.fr][Licence Creative Commons Attribution - Pas de Modification 3.0 France]]

[[http://creativecommons.org/licenses/by-nd/3.0/fr/deed.fr][file:http://i.creativecommons.org/l/by-nd/3.0/80x15.png]]
* Licenza
Todo o texto está dispoñible baixo a [[http://creativecommons.org/licenses/by-nd/3.0/es/deed.gl][licenza Creative Commons recoñecemento compartir igual 3.0]].

[[http://creativecommons.org/licenses/by-nd/3.0/es/deed.gl][file:http://i.creativecommons.org/l/by-nd/3.0/80x15.png]]
* Licenza
Quest'opera e distribuita con Licenza [[http://creativecommons.org/licenses/by-nd/3.0/it/deed.it][Licenza Creative Commons Attribuzione - Non opere derivate 3.0 Italia]]

[[http://creativecommons.org/licenses/by-nd/3.0/it/deed.it][file:http://i.creativecommons.org/l/by-nd/3.0/80x15.png]]
* Licença
Este texto é disponibilizado nos termos da licença [[http://creativecommons.org/licenses/by-nd/3.0/pt/deed.pt][Atribuição Sem Derivados 3.0 Portugal]]

[[http://creativecommons.org/licenses/by-nd/3.0/pt/deed.pt][file:http://i.creativecommons.org/l/by-nd/3.0/80x15.png]]
* Licença
Este texto é disponibilizado nos termos da licença [[https://creativecommons.org/licenses/by-nc/3.0/br/deed.pt_BR][Atribuição Não Comercial 3.0 Brasil]]

[[https://creativecommons.org/licenses/by-nc/3.0/br/deed.pt_BR][file:http://i.creativecommons.org/l/by-nc/3.0/80x15.png]]
* Licència
El text està disponible sota la [[http://creativecommons.org/licenses/by-nc/3.0/es/deed.ca][Reconeixement-NoComercial 3.0 Espanya]]

[[http://creativecommons.org/licenses/by-nc/3.0/es/deed.ca][file:http://i.creativecommons.org/l/by-nc/3.0/80x15.png]]
* Lizenz
Dieses Werk bzw. Inhalt steht unter einer [[http://creativecommons.org/licenses/by-nc/3.0/de/deed.de][Namensnennung-Nicht-kommerziell 3.0 Deutschland]]

[[http://creativecommons.org/licenses/by-nc/3.0/de/deed.de][file:http://i.creativecommons.org/l/by-nc/3.0/80x15.png]]
* Licencia
Este documento está bajo una [[http://creativecommons.org/licenses/by-nc/3.0/es/deed.es][Licencia Creative Commons Reconocimiento-NoComercial 3.0]]

[[http://creativecommons.org/licenses/by-nc/3.0/es/deed.es][file:http://i.creativecommons.org/l/by-nc/3.0/80x15.png]]
* License 
This document is under a [[http://creativecommons.org/licenses/by-nc/3.0/deed][Creative Commons Attribution-NonCommercial 3.0 Unported]]

[[http://creativecommons.org/licenses/by-nc/3.0/deed][file:http://i.creativecommons.org/l/by-nc/3.0/80x15.png]]
* Licenzua
Testua [[http://creativecommons.org/licenses/by-nc/3.0/es/deed.eu][Aitortu-EzKomertziala 3.0 Espainia]] lizentziari jarraituz erabil daiteke

[[http://creativecommons.org/licenses/by-nc/3.0/es/deed.eu][file:http://i.creativecommons.org/l/by-nc/3.0/80x15.png]]
* Lisenssi
Teksti on saatavilla [[http://creativecommons.org/licenses/by-nc/1.0/fi/deed.fi][Nimeä-Epäkaupallinen 1.0 Suomi]] lisenssillä

[[http://creativecommons.org/licenses/by-nc/1.0/fi/deed.fi][file:http://i.creativecommons.org/l/by-nc/3.0/80x15.png]]
* Licence
Ce(tte) œuvre est mise à disposition selon les termes de la [[http://creativecommons.org/licenses/by-nc/3.0/fr/deed.fr][Licence Creative Commons Attribution - Pas d'Utilisation Commerciale 3.0 France]]

[[http://creativecommons.org/licenses/by-nc/3.0/fr/deed.fr][file:http://i.creativecommons.org/l/by-nc/3.0/80x15.png]]
* Licenza
Todo o texto está dispoñible baixo a [[http://creativecommons.org/licenses/by-nc/3.0/es/deed.gl][licenza Creative Commons recoñecemento compartir igual 3.0]].

[[http://creativecommons.org/licenses/by-nc/3.0/es/deed.gl][file:http://i.creativecommons.org/l/by-nc/3.0/80x15.png]]
* Licenza
Quest'opera e distribuita con Licenza [[http://creativecommons.org/licenses/by-nc/3.0/it/deed.it][Licenza Creative Commons Attribuzione - Non commerciale 3.0 Italia]]

[[http://creativecommons.org/licenses/by-nc/3.0/it/deed.it][file:http://i.creativecommons.org/l/by-nc/3.0/80x15.png]]
* Licença
Este texto é disponibilizado nos termos da licença [[http://creativecommons.org/licenses/by-nc/3.0/pt/deed.pt][Atribuição Não Comercial 3.0 Portugal]]

[[http://creativecommons.org/licenses/by-nc/3.0/pt/deed.pt][file:http://i.creativecommons.org/l/by-nc/3.0/80x15.png]]
* Licença
Este texto é disponibilizado nos termos da licença [[https://creativecommons.org/licenses/by-nc-sa/3.0/br/deed.pt_BR][Atribuição Não Comercial - Compartil ha Igual 3.0 Brasil]]

[[https://creativecommons.org/licenses/by-nc-sa/3.0/br/deed.pt_BR][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]
* Licència
El text està disponible sota la [[http://creativecommons.org/licenses/by-nc-sa/3.0/es/deed.ca][Reconeixement-NoComercial 3.0 Espanya]]

[[http://creativecommons.org/licenses/by-nc-sa/3.0/es/deed.ca][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]
* Lizenz
Dieses Werk bzw. Inhalt steht unter einer [[http://creativecommons.org/licenses/by-nc-sa/3.0/de/deed.de][Namensnennung - Weitergabe unter gleichen Bedingungen 3.0 Deutschland]]

[[http://creativecommons.org/licenses/by-nc-sa/3.0/de/deed.de][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]
* Licencia
Este documento está bajo una [[http://creativecommons.org/licenses/by-nc-sa/3.0/es/deed.es][Licencia Creative Commons Reconocimiento-NoComercial 3.0]]

[[http://creativecommons.org/licenses/by-nc-sa/3.0/es/deed.es][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]
* License
This document is under a [[http://creativecommons.org/licenses/by-nc-sa/3.0/deed][License Creative Commons
Reconocimiento-NoComercial 3.0 Unported]]

[[http://creativecommons.org/licenses/by-nc-sa/3.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]
* Licenzua
Testua [[http://creativecommons.org/licenses/by-nc-sa/3.0/es/deed.eu][Aitortu-EzKomertziala-PartekatuBerdin 3.0 Espainia]] lizentziari jarraituz erabil daiteke

[[http://creativecommons.org/licenses/by-nc-sa/3.0/es/deed.eu][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]
* Lisenssi
Teksti on saatavilla [[http://creativecommons.org/licenses/by-nc-sa/1.0/fi/deed.fi][Nimeä-Epäkaupallinen-JaaSamoin 1.0 Suomi]] lisenssillä

[[http://creativecommons.org/licenses/by-nc-sa/1.0/fi/deed.fi][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]
* Licence
Ce(tte) œuvre est mise à disposition selon les termes de la [[http://creativecommons.org/licenses/by-nc-sa/3.0/fr/deed.fr][Licence Creative Commons Attribution - Pas d’Utilisation Commerciale - Partage dans les Mêmes Conditions 3.0 France]]

[[http://creativecommons.org/licenses/by-nc-sa/3.0/fr/deed.fr][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]
* Licenza
Todo o texto está dispoñible baixo a [[http://creativecommons.org/licenses/by-nc-sa/3.0/es/deed.gl][licenza Creative Commons recoñecemento compartir igual 3.0]].

[[http://creativecommons.org/licenses/by-nc-sa/3.0/es/deed.gl][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]
* Licenza
Quest'opera e distribuita con Licenza [[http://creativecommons.org/licenses/by-nc-sa/3.0/it/deed.it][Licenza Creative Commons Attribuzione - Non opere derivate 3.0 Italia]]

[[http://creativecommons.org/licenses/by-nc-sa/3.0/it/deed.it][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]
* Licença
Este texto é disponibilizado nos termos da licença [[http://creativecommons.org/licenses/by-nc/3.0/pt/deed.pt][Atribuição NãoComercial Compartil ha Igual 3.0 Portugal]]

[[http://creativecommons.org/licenses/by-nc/3.0/pt/deed.pt][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]
* Licença
Este texto é disponibilizado nos termos da licença [[http://creativecommons.org/licenses/by-nc-nd/3.0/pt/deed.pt][Atribuição Não Comercial Sem Derivados 3.0 Brasil]]

[[http://creativecommons.org/licenses/by-nc-nd/3.0/pt/deed.pt][file:http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png]]
* Licència
El text està disponible sota la [[http://creativecommons.org/licenses/by-nc-nd/3.0/es/deed.ca][Reconeixement-NoComercial-SenseObraDerivada 3.0 Espanya]]

[[http://creativecommons.org/licenses/by-nc-nd/3.0/es/deed.ca][file:http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png]]
* Lizenz
Dieses Werk bzw. Inhalt steht unter einer [[http://creativecommons.org/licenses/by-nc-nd/3.0/de/deed.de][Namensnennung-NichtKommerziell-KeineBearbeitung 3.0 Deutschland]]

[[http://creativecommons.org/licenses/by-nc-nd/3.0/de/deed.de][file:http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png]]
* Licencia 
Este documento está bajo una [[http://creativecommons.org/licenses/by-nc-nd/3.0/es/deed.es][Licencia Creative Commons Reconocimiento-NoComercial-SinObraDerivada 3.0]]

[[http://creativecommons.org/licenses/by-nc-nd/3.0/es/deed.es][file:http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png]]
* License
This document is under a [[http://creativecommons.org/licenses/by-nc-nd/3.0/deed][License Creative Commons
Reconocimiento-NoComercial-SinObraDerivada 3.0 Unported]]

[[http://creativecommons.org/licenses/by-nc-nd/3.0/deed][file:http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png]]
* Licenzua
Testua [[http://creativecommons.org/licenses/by-nc-nd/3.0/es/deed.eu][Aitortu-LanEratorririkGabe 3.0 Espainia]] lizentziari jarraituz erabil daiteke

[[http://creativecommons.org/licenses/by-nc-nd/3.0/es/deed.eu][file:http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png]]
* Lisenssi
Teksti on saatavilla [[http://creativecommons.org/licenses/by-nc-nd/1.0/fi/deed.fi][Nimeä-Ei muutoksia-Epäkaupallinen 1.0 Suomi]] lisenssillä

[[http://creativecommons.org/licenses/by-nc-nd/1.0/fi/deed.fi][file:http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png]]
* Licence
Ce(tte) œuvre est mise à disposition selon les termes de la [[http://creativecommons.org/licenses/by-nc-nd/3.0/fr/deed.fr][Licence Creative Commons Attribution - Pas de Modification 3.0 France]]

[[http://creativecommons.org/licenses/by-nc-nd/3.0/fr/deed.fr][file:http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png]]
* Licenza
Todo o texto está dispoñible baixo a [[http://creativecommons.org/licenses/by-nc-nd/3.0/es/deed.gl][licenza Creative Commons recoñecemento compartir igual 3.0]].

[[http://creativecommons.org/licenses/by-nc-nd/3.0/es/deed.gl][file:http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png]]
* Licenza
Quest'opera e distribuita con Licenza [[http://creativecommons.org/licenses/by-nc-nd/3.0/it/deed.it][Licenza Creative Commons Attribuzione - Non opere derivate 3.0 Italia]]

[[http://creativecommons.org/licenses/by-nc-nd/3.0/it/deed.it][file:http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png]]
* Licença
Este texto é disponibilizado nos termos da licença [[http://creativecommons.org/licenses/by-nc-nd/3.0/pt/deed.pt][Atribuição Não Comercial Sem Derivados 3.0 Portugal]]

[[http://creativecommons.org/licenses/by-nc-nd/3.0/pt/deed.pt][file:http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png]]
