<?php

/**
 * @file
 * This module transform an org file to nodes
 */

/**
 * Implements hook_menu().
 *
 * Here we set up the URLs (menu entries) for the
 * form examples. Note that most of the menu items
 * have page callbacks and page arguments set, with
 * page arguments set to be functions in external files.
 *
 */

function orgmode_menu() {
  $items = array();
  $items['orgmode'] = array(
    'title' => 'Org Mode Import',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('orgmode_form_upload'),
    'description' => 'Org Mode Import',
    'access callback' => array('_node_add_access'),
    'file' => 'orgmode.inc',
    'weight' => 10,
  );
  return $items;
}

?>